"""Web audio manifest generation for Howler, Phaser, and native Web Audio."""

from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path


def write_audio_manifest(
    output_dir: Path,
    music: Iterable[tuple[str, str, str]],
    sfx: Iterable[tuple[str, str, str]],
) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    def entries(items, loop):
        return {
            key: {
                "ogg": f"audio/{ogg_name}",
                "mp3": f"audio/{mp3_name}",
                "loop": loop,
            }
            for key, ogg_name, mp3_name in items
        }

    manifest: dict[str, object] = {
        "music": entries(music, True),
        "sfx": entries(sfx, False),
    }
    body = json.dumps(manifest, ensure_ascii=False, indent=2)
    path = output_dir / "AudioManifest.js"
    path.write_text(
        f"// Generated by Blipkit. Do not edit by hand.\nexport const AudioManifest = {body};\n",
        encoding="utf-8",
    )
    return path
